routes/web.php
<?php

use App\Http\Controllers\SettingsController;
use App\Models\User;
use App\Scopes\YanipScope;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Middleware\TenantMiddleware;
use App\Http\Controllers\TenantsController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AttendancesController;
use App\Http\Controllers\auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('auth/login/index');
});


Route::namespace('Auth')->name('auth.')->prefix('auth/')->group(function ()
{
    Route::name('login.')->prefix('login/')->group(function ()
    {
        Route::get('index',[LoginController::class, 'index'])->name('index');
        Route::post('process',[LoginController::class, 'store'])->name('store');
    });
    Route::name('register.')->prefix('register/')->group(function ()
    {
        Route::get('/index', [RegisterController::class, 'index'])->name('index');
        Route::get('/proccess', [RegisterController::class, 'store'])->name('store');
    });
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});

/**
 * Admin Area
 */
Route::group(['middleware' => ['role:superadmin|staff|admin', 'auth']], function () {

    Route::name('admin.')->prefix('/admin')->group(function ()
    {
        // Route::get('attendances/export')
        Route::post('attendances/lists', 'Admin\AttendancesController@lists')->name('attendances.lists');
        Route::post('attendances/lists/filter', 'Admin\AttendancesController@show')->name('attendances.lists.filter');
        Route::post('paid-leaves/lists', 'Admin\PaidLeaveController@lists')->name('paid-leaves.lists');
        Route::post('dinas/lists', 'Admin\DinasController@lists')->name('dinas.lists');

        Route::get('paid-leaves/show/{cat_id}/{user_id}', 'Admin\PaidLeaveController@showByCatIDnUserID')->name('paid-leaves.showByCatIDnUserID');
        Route::get('paid-leaves/users', 'Admin\PaidLeaveController@lists_users')->name('paid-leaves.users.lists');
        Route::resource('paid-leaves', 'Admin\PaidLeaveController');
        Route::resource('sick-leaves', 'Admin\SickLeaveController');

        Route::resource('attendances', 'Admin\AttendancesController');
        Route::resource('dinas', 'Admin\DinasController');

        Route::get('/clear-cahce', function (){Artisan::call('cache:clear');});
        Route::post('update-password', 'UserController@updatePassword')->name('update-password');
    });

});

Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard', 'Admin\HomeController@index')->name('staff.dashboard');
    Route::get('dashboard/show-detail/{user_id}/{module}', 'Admin\HomeController@show')->name('show.detail.module');
    Route::post('notifications/store', 'NotificationController@store')->name('send.notification.store');
});


// Superadmin
Route::group(['middleware' => ['role:superadmin|staff', 'auth']], function () {

    Route::post('import', 'Admin\AttendancesController@import')->name('attendance.import');
    Route::get('export', 'Admin\AttendancesController@export')->name('attendance.export');

    Route::resource('users','Admin\UserController');
    Route::post('users', 'Admin\UserController@import')->name('users.import');
    Route::post('users/store', 'Admin\UserController@store')->name('users.store');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions','Admin\PermissionController');

    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::resource('dinas','DinasController');

    Route::post('lists/users', 'Admin\HomeController@lists')->name('admin.dashboard.lists');

    Route::resource('settings', 'SettingsController');
});

// PJLP
Route::group(['middleware' => ['role:pjlp|staff', 'auth']], function () {
    Route::post('attendances/lists', 'AttendancesController@lists')->name('attendances.lists');
    Route::get('dashboard-pjlp', 'HomeController@index')->name('dashboard');
    Route::post('attendance', 'AttendancesController@store')->name('attendance.store');
    Route::get('attendance', 'AttendancesController@index')->name('attendance.index');
    Route::resource('dinas','DinasController');
    Route::post('paid-leaves/sick', 'PaidLeavesController@sick')->name('paid-leave.sick');
    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::post('update-password', 'UserController@updatePassword')->name('update-password');
});

// Admin
Route::group(['middleware' => ['role:admin', 'auth']], function () {

});

Route::group(['middleware' => ['auth']], function () {
    Route::post('auth/sip', 'Auth\LoginController@loginFromOtherSite');
});

app/Http/Controllers/Admin/PermissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
        $this->middleware('permission:permission-list');
        $this->middleware('permission:permission-create', ['only' => ['create','store']]);
        $this->middleware('permission:permission-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:permission-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users =
        $permissions = Permission::orderBy('id','DESC')->paginate(5);
        $pageTitle = 'Permission Manajemen';
        return view('admin.pages.permissions.index',compact('permissions', 'pageTitle'))
            ->with('i', ($request->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permission = Permission::get();
        $pageTitle = 'Permission Manajemen';
        return view('admin.pages.roles.create',compact('permission', 'pageTitle'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::find($request->user_id);
        $user->syncPermissions($request->permission_id);
        return redirect()->route('users.index')
                        ->with('success','Permissions created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/permissions/create.blade.php
@extends('layouts.app-lte')
@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @include('components.alert')
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <div class="pull-right">
                                <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
                            </div>
                        </h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">

                        {!! Form::open(array('route' => 'admin.roles.store','method'=>'POST')) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {!! Form::text('name', null, array('placeholder' => 'Name','class' =>
                                    'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Permission:</strong>
                                    <br />
                                    @foreach($permission as $value)
                                    <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' =>
                                        'name')) }}
                                        {{ $value->name }}</label>
                                    <br />
                                    @endforeach
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                        {!! Form::close() !!}

                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        Footer
                    </div>
                    <!-- /.card-footer-->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
<!-- /.content -->
@endsection
@section('js-section')

@endsection

resources/views/admin/pages/permissions/edit.blade.php
@extends('layouts.app-lte')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit Role</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
        </div>
    </div>
</div>


@if (count($errors) > 0)
    <div class="alert alert-danger">
        <strong>Whoops!</strong> There were some problems with your input.<br><br>
        <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
        </ul>
    </div>
@endif


{!! Form::model($role, ['method' => 'PATCH','route' => ['roles.update', $role->id]]) !!}
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {!! Form::text('name', null, array('placeholder' => 'Name','class' => 'form-control')) !!}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permission:</strong>
            <br/>
            @foreach($permission as $value)
                <label>{{ Form::checkbox('permission[]', $value->id, in_array($value->id, $rolePermissions) ? true : false, array('class' => 'name')) }}
                {{ $value->name }}</label>
            <br/>
            @endforeach
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</div>
{!! Form::close() !!}


@endsection

resources/views/admin/pages/permissions/index.blade.php
@extends('layouts.app-lte')
@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @include('components.alert')
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <div class="pull-right">
                                @can('permission-create')
                                    <a class="btn btn-success" href="{{ route('permissions.create') }}"> Create New Permission</a>
                                @endcan
                                </div>
                        </h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">

                        <table class="table table-bordered">
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th width="280px">Action</th>
                            </tr>
                            {{-- @foreach ($roles as $key => $role)
                            <tr>
                                <td>{{ ++$i }}</td>
                                <td>{{ $role->name }}</td>
                                <td>
                                    <a class="btn btn-info" href="{{ route('permissions.show',$role->id) }}">Show</a>
                                    @can('role-edit')
                                    <a class="btn btn-primary" href="{{ route('permissions.edit',$role->id) }}">Edit</a>
                                    @endcan
                                    @can('role-delete')
                                    {!! Form::open(['method' => 'DELETE','route' => ['permissions.destroy',
                                    $role->id],'style'=>'display:inline']) !!}
                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                                    {!! Form::close() !!}
                                    @endcan
                                </td>
                            </tr>
                            @endforeach --}}
                        </table>


                        {{-- {!! $roles->render() !!} --}}

                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        Footer
                    </div>
                    <!-- /.card-footer-->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
<!-- /.content -->
@endsection
@section('js-section')

@endsection

resources/views/admin/pages/permissions/show.blade.php
@extends('layouts.app-lte')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Role</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{-- {{ $role->name }} --}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permissions:</strong>
            @if(!empty($rolePermissions))
                @foreach($rolePermissions as $v)
                    <label class="label label-success">{{ $v->name }},</label>
                @endforeach
            @endif
        </div>
    </div>
</div>
@endsection