routes/web.php
<?php

use App\Http\Controllers\SettingsController;
use App\Models\User;
use App\Scopes\YanipScope;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Middleware\TenantMiddleware;
use App\Http\Controllers\TenantsController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AttendancesController;
use App\Http\Controllers\auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('auth/login/index');
});


Route::namespace('Auth')->name('auth.')->prefix('auth/')->group(function ()
{
    Route::name('login.')->prefix('login/')->group(function ()
    {
        Route::get('index',[LoginController::class, 'index'])->name('index');
        Route::post('process',[LoginController::class, 'store'])->name('store');
    });
    Route::name('register.')->prefix('register/')->group(function ()
    {
        Route::get('/index', [RegisterController::class, 'index'])->name('index');
        Route::get('/proccess', [RegisterController::class, 'store'])->name('store');
    });
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});

/**
 * Admin Area
 */
Route::group(['middleware' => ['role:superadmin|staff|admin', 'auth']], function () {

    Route::name('admin.')->prefix('/admin')->group(function ()
    {
        // Route::get('attendances/export')
        Route::post('attendances/lists', 'Admin\AttendancesController@lists')->name('attendances.lists');
        Route::post('attendances/lists/filter', 'Admin\AttendancesController@show')->name('attendances.lists.filter');
        Route::post('paid-leaves/lists', 'Admin\PaidLeaveController@lists')->name('paid-leaves.lists');
        Route::post('dinas/lists', 'Admin\DinasController@lists')->name('dinas.lists');

        Route::get('paid-leaves/show/{cat_id}/{user_id}', 'Admin\PaidLeaveController@showByCatIDnUserID')->name('paid-leaves.showByCatIDnUserID');
        Route::get('paid-leaves/users', 'Admin\PaidLeaveController@lists_users')->name('paid-leaves.users.lists');
        Route::resource('paid-leaves', 'Admin\PaidLeaveController');
        Route::resource('sick-leaves', 'Admin\SickLeaveController');

        Route::resource('attendances', 'Admin\AttendancesController');
        Route::resource('dinas', 'Admin\DinasController');

        Route::get('/clear-cahce', function (){Artisan::call('cache:clear');});
        Route::post('update-password', 'UserController@updatePassword')->name('update-password');
    });

});

Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard', 'Admin\HomeController@index')->name('staff.dashboard');
    Route::get('dashboard/show-detail/{user_id}/{module}', 'Admin\HomeController@show')->name('show.detail.module');
    Route::post('notifications/store', 'NotificationController@store')->name('send.notification.store');
});


// Superadmin
Route::group(['middleware' => ['role:superadmin|staff', 'auth']], function () {

    Route::post('import', 'Admin\AttendancesController@import')->name('attendance.import');
    Route::get('export', 'Admin\AttendancesController@export')->name('attendance.export');

    Route::resource('users','Admin\UserController');
    Route::post('users', 'Admin\UserController@import')->name('users.import');
    Route::post('users/store', 'Admin\UserController@store')->name('users.store');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions','Admin\PermissionController');

    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::resource('dinas','DinasController');

    Route::post('lists/users', 'Admin\HomeController@lists')->name('admin.dashboard.lists');

    Route::resource('settings', 'SettingsController');
});

// PJLP
Route::group(['middleware' => ['role:pjlp|staff', 'auth']], function () {
    Route::post('attendances/lists', 'AttendancesController@lists')->name('attendances.lists');
    Route::get('dashboard-pjlp', 'HomeController@index')->name('dashboard');
    Route::post('attendance', 'AttendancesController@store')->name('attendance.store');
    Route::get('attendance', 'AttendancesController@index')->name('attendance.index');
    Route::resource('dinas','DinasController');
    Route::post('paid-leaves/sick', 'PaidLeavesController@sick')->name('paid-leave.sick');
    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::post('update-password', 'UserController@updatePassword')->name('update-password');
});

// Admin
Route::group(['middleware' => ['role:admin', 'auth']], function () {

});

Route::group(['middleware' => ['auth']], function () {
    Route::post('auth/sip', 'Auth\LoginController@loginFromOtherSite');
});

app/Http/Controllers/Admin/DinasController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Dinas;
use App\Traits\UploadTrait;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Services;
use App\Repository\Dinas\DinasRepository;

class DinasController extends Controller
{
    use UploadTrait;
    protected $dinas;
    public function __construct(DinasRepository $dinasRepository) {
        $this->dinas = $dinasRepository;
    }
        /**
         * Display a listing of the resource.
         *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pageTitle = 'dinas';
        return view('admin.pages.dinas.index', [
            'pageTitle' => $pageTitle
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        list($date_start, $date_end) = explode(' s/d ', $request->service_date);
        $request['date_start'] = $date_start;
        $request['date_end'] = $date_end;

        try {
            $path = 'uploads/dinas/'.date('Y-m-d').'/';
            $surat_dinas = $this->uploadSuratDinas($path, $request->file('surat_dinas'));
            $request['letter_of_assignment'] = $surat_dinas;
        } catch (\Throwable $th) {
            dd($th->getMessage());
        }

        $dinas = $this->dinas->create($request->all());

        if ($dinas) {
            return redirect('/admin/dinas')->with(['success' => 'Berhasil Input Perjalanan Dinas']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Dinas  $dinas
     * @return \Illuminate\Http\Response
     */
    public function show(Dinas $dinas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Dinas  $dinas
     * @return \Illuminate\Http\Response
     */
    public function edit(Dinas $dinas)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Dinas  $dinas
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dinas $dinas)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Dinas  $dinas
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dinas $dinas)
    {
        //
    }

    public function lists(Request $request) {
        $pageNumber = ( $request->start / $request->length )+1;
        $pageLength = $request->length;
        $skip       = ($pageNumber-1) * $pageLength;

        // Page Order
        $orderColumnIndex = $request->order[0]['column'] ?? '0';
        $orderBy = $request->order[0]['dir'] ?? 'desc';


        // Search
        //  get data from products table
        $search = $request->search;
        $query = Services::where('service_description', 'like', "%".$search."%")
                    ->orWhere('name', 'like', "%".$search."%")
                    ->orWhere('service_number', 'like', "%".$search."%")
                    ->orWhere('service_date_start', 'like', "%".$search."%")
                    ->orWhere('service_date_end', 'like', "%".$search."%")
                    ->with(['Details.User' => function($query) use($search) {
                        $query->orWhere('name', 'like', "%".$search."%")->get();
                    }, 'Category' => function($query) use ($search) {
                        $query->orWhere('name', 'like', "%".$search."%")->get();
                    }, 'CommissionedBy' => function($query) use($search) {
                        $query->orWhere('name', 'like', "%".$search."%")->get();
                    }]);

        // $orderByName = 'name';
        // switch($orderColumnIndex){
        //     case '0':
        //         $orderByName = 'name';
        //         break;
        //     case '1':
        //         $orderByName = 'email';
        //         break;
        // }
        // $query = $query->orderBy($orderByName, $orderBy);
        $recordsFiltered = $recordsTotal = $query->count();
        $data = $query->skip($skip)->take($pageLength)->get();

        return response()->json(["draw"=> $request->draw, "recordsTotal"=> $recordsTotal, "recordsFiltered" => $recordsFiltered, 'data' => $data], 200);
    }
}

app/Http/Controllers/DinasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Services;
use App\Models\ServicesDetail;
use App\Repository\Dinas\DinasRepository;
use App\Traits\DinasTrait;
use Illuminate\Http\Request;

class DinasController extends Controller
{
    use DinasTrait;
    protected $dinas;
    public function __construct(
        DinasRepository $dinasRepository
        ) {
        $this->dinas = $dinasRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pageTitle = 'dinas';

        $services = Services::whereHas('Details', function ($query)  {
            $query->where('user_id', auth()->user()->id);
        })->get();
        return view('dinas', [
            'pageTitle' => $pageTitle,
            'data' => $services
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dinas = $this->dinas->show($request->dinas_id);
        // dd($dinas);
        $this->checkCategoryDinasID($dinas->service_cat_id, ['start' => $dinas->service_date_start, 'end' => $dinas->service_date_end]);
        if($this->dinas->approve($request->dinas_id)) {
            return redirect()->back()->with(['success' => 'Berhasil Terima Dinas']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Services  $services
     * @return \Illuminate\Http\Response
     */
    public function show(Services $services)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Services  $services
     * @return \Illuminate\Http\Response
     */
    public function edit(Services $services)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Services  $services
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Services $services)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Services  $services
     * @return \Illuminate\Http\Response
     */
    public function destroy(Services $services)
    {
        //
    }
}

resources/views/admin/pages/dinas/index.blade.php
@extends('layouts.app-lte')
@section('css-section')
    <link rel="stylesheet" href="{{ asset('v2/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('v2/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('v2/plugins/datatables-buttons/css/buttons.bootstrap4.min.css') }}">
<!-- Select2 -->
  <link rel="stylesheet" href="{{asset('v2/plugins/select2/css/select2.min.css')}}">
  <link rel="stylesheet" href="{{asset('v2/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
  <!-- daterange picker -->
  <link rel="stylesheet" href="{{asset('v2/plugins/daterangepicker/daterangepicker.css')}}">
  <style>
    tbody tr {
        position: relative;
    }
  </style>

@endsection

@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @include('components.alert')
        <div class="row">
            <div class="col-md-3 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Tambah Perjalanan untuk PJLP </h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        {!! Form::open(array('route' => 'admin.dinas.store','method'=>'POST', 'enctype' => 'multipart/form-data')) !!}
                        <div class="form-group">
                            <strong>Nomor Surat Dinas:</strong>
                            {!! Form::text('name', null, array('placeholder' => 'Nomor Surat Dinas','class' => 'form-control', 'required' => 'required')) !!}
                        </div>
                        <div class="form-group">
                            <strong>Yang Ditugaskan:</strong>
                            {!! Form::select('user_id[]', \App\Models\User::Role('pjlp')->pluck('name', 'id')->toArray(), '', ['class' => 'form-control select2', 'multiple' => "multiple", 'data-placeholder'=>"Pilih User", 'required' => 'required']) !!}
                        </div>
                        <div class="form-group">
                            <strong>Kategori Dinas:</strong>
                            {!! Form::select('service_cat_id', ['' => 'Pilih Kategori Dinas']+\App\Models\ServicesCat::whereFlag('enabled')->pluck('name', 'id')->toArray(), '', ['class' => 'form-control', 'data-placeholder'=>"Pilih Kategori Dinas", 'required' => 'required']) !!}
                        </div>
                        @component('components.date-range', [
                            'label' => 'Tanggal Perjalanan Dinas',
                            'name' => 'service_date'
                        ])
                        @endcomponent
                        <div class="form-group">
                            <strong>Deskripsi Dinas:</strong>
                            {!! Form::textarea('service_description', null, array('placeholder' => 'Deskripsi Dinas','class' => 'form-control', 'rows' => 3, 'cols' => '2')) !!}
                        </div>
                        <div class="form-group">
                            <strong>Surat Dinas</strong>
                            {{Form::file('surat_dinas',['class'=>'form-control'])}}
                        </div>

                        <div class="form-group">
                            {!! Form::submit('Simpan', ['class' => 'btn btn-block btn-success']) !!}
                        </div>

                        {!! Form::close() !!}
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
            <div class="col-md-9 col-sm-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">List Perjalanan {{ $pageTitle }} PJLP</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <table  id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nomor Perjalanan Dinas</th>
                                    <th>Detail Perjalanan Dinas</th>
                                    <th>Yang Ditugaskan</th>
                                    <th>Pemberi Tugas</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
                <!-- /.card -->

            </div>
        </div>
</section>
@section('js-section')
    <script src="{{ asset('v2/plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/jszip/jszip.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/pdfmake/pdfmake.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/pdfmake/vfs_fonts.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('v2/plugins/datatables-buttons/js/buttons.colVis.min.js') }}"></script>
    <!-- Select2 -->
    <script src="{{asset('v2/plugins/select2/js/select2.full.min.js')}}"></script>
    <!-- Moment -->
    <script src="{{asset('v2/plugins/moment/moment.min.js')}}"></script>
    <!-- date-range-picker -->
    <script src="{{asset('v2/plugins/daterangepicker/daterangepicker.js')}}"></script>

    <script>
        $(function () {
            //Select2
            $('.select2').select2()

            //Date range picker
            $('#daterangecustom').daterangepicker({
                opens: 'rigth',
                drops: 'up',
                locale: {
                    format: 'DD-MM-YYYY',
                    separator: " s/d "
                },function(start, end, label) {
                   console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
                }
            })

        });

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $("#example1").DataTable({
            "responsive": true,
            "lengthChange": false,
            "autoWidth": false,
            "processing": true,
            "serverSide": true,
            "ajax": {
                "url": "{{ route('admin.dinas.lists') }}",
                "type": "POST",
                "data": function (data) {
                    data.search = $('input[type="search"]').val();
                }
            },
            "order": ['1', 'DESC'],
            "pageLength": 10,
            "searching": true,
            "aoColumns": [
                    {
                        data: null,
                        render: function(data, type, row) {
                            var url_edit = "{{route('admin.dinas.edit', ':slug')}}"
                            url_edit = url_edit.replace(':slug', data.id)
                            let today = new Date().toISOString().slice(0, 10)

                            var url_destroy = "{{route('admin.dinas.destroy', ':slug')}}"
                            url_destroy = url_destroy.replace(':slug', data.id)
                            return `<strong>${row.name}</strong><br>Dibuat : <br>${row.created_at_humans} </br> <img src="/uploads/dinas/${today}/${row.letter_of_assignment}" class="mailbox-attachment-icon has-img"> <div style="position:absolute; bottom: 0; margin-block-end: 10px;"><a class="btn btn-success" href="${url_edit}">Edit</a> <a class="btn btn-danger" href="${url_destroy}">Hapus</a></div> `
                        }
                    },
                    {
                        data: null,
                        render: function(data, type, row) {
                            var html = `<table style="width:100%">
                                    <tr>
                                        <th>Kategori Dinas</th>
                                        <td>${row.category.name}</td>
                                    </tr>
                                    <tr>
                                        <th>Deskripsi Dinas</th>
                                        <td>${row.description_ellipsis}</td>
                                    </tr>

                                    <tr>
                                        <th>Tanggal Perjalanan Dinas</th>
                                        <td><strong>${row.tanggal_mulai_dinas}</strong> <br>Sampai Dengan<br> <strong>${row.tanggal_akhir_dinas}</strong></td>
                                    </tr>
                                    </table>`
                                    return html;
                        }
                    },

                    {
                        data: 'details',
                        render: function(data, type, row) {
                            var assign_for = `<table style="width:100%">`
                            data.forEach(element => {
                                if (element.flag == 'submit') {
                                    var flag = `<span class="badge badge-danger">Belum Diterima User PJLP</span>`
                                }else{
                                    var flag = `<span class="badge badge-success">Sudah Diterima User PJLP</span>`
                                }
                                assign_for += `<tr>`
                                    assign_for += `<th>${element.user.name}</th>`
                                    assign_for += `<td>${flag}</td>`
                                assign_for += `</tr>`
                            });
                            assign_for += `</table>`;
                            return assign_for;
                        }
                    },
                    {
                        data: 'commissioned_by.name',
                    },

            ],
            columnDefs: [{
                "defaultContent": "-",
                "targets": "_all"
            }]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    </script>

@endsection
@endsection