routes/web.php
<?php

use App\Http\Controllers\SettingsController;
use App\Models\User;
use App\Scopes\YanipScope;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Middleware\TenantMiddleware;
use App\Http\Controllers\TenantsController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AttendancesController;
use App\Http\Controllers\auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('auth/login/index');
});


Route::namespace('Auth')->name('auth.')->prefix('auth/')->group(function ()
{
    Route::name('login.')->prefix('login/')->group(function ()
    {
        Route::get('index',[LoginController::class, 'index'])->name('index');
        Route::post('process',[LoginController::class, 'store'])->name('store');
    });
    Route::name('register.')->prefix('register/')->group(function ()
    {
        Route::get('/index', [RegisterController::class, 'index'])->name('index');
        Route::get('/proccess', [RegisterController::class, 'store'])->name('store');
    });
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});

/**
 * Admin Area
 */
Route::group(['middleware' => ['role:superadmin|staff|admin', 'auth']], function () {

    Route::name('admin.')->prefix('/admin')->group(function ()
    {
        // Route::get('attendances/export')
        Route::post('attendances/lists', 'Admin\AttendancesController@lists')->name('attendances.lists');
        Route::post('attendances/lists/filter', 'Admin\AttendancesController@show')->name('attendances.lists.filter');
        Route::post('paid-leaves/lists', 'Admin\PaidLeaveController@lists')->name('paid-leaves.lists');
        Route::post('dinas/lists', 'Admin\DinasController@lists')->name('dinas.lists');

        Route::get('paid-leaves/show/{cat_id}/{user_id}', 'Admin\PaidLeaveController@showByCatIDnUserID')->name('paid-leaves.showByCatIDnUserID');
        Route::get('paid-leaves/users', 'Admin\PaidLeaveController@lists_users')->name('paid-leaves.users.lists');
        Route::resource('paid-leaves', 'Admin\PaidLeaveController');
        Route::resource('sick-leaves', 'Admin\SickLeaveController');

        Route::resource('attendances', 'Admin\AttendancesController');
        Route::resource('dinas', 'Admin\DinasController');

        Route::get('/clear-cahce', function (){Artisan::call('cache:clear');});
        Route::post('update-password', 'UserController@updatePassword')->name('update-password');
    });

});

Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard', 'Admin\HomeController@index')->name('staff.dashboard');
    Route::get('dashboard/show-detail/{user_id}/{module}', 'Admin\HomeController@show')->name('show.detail.module');
    Route::post('notifications/store', 'NotificationController@store')->name('send.notification.store');
});


// Superadmin
Route::group(['middleware' => ['role:superadmin|staff', 'auth']], function () {

    Route::post('import', 'Admin\AttendancesController@import')->name('attendance.import');
    Route::get('export', 'Admin\AttendancesController@export')->name('attendance.export');

    Route::resource('users','Admin\UserController');
    Route::post('users', 'Admin\UserController@import')->name('users.import');
    Route::post('users/store', 'Admin\UserController@store')->name('users.store');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions','Admin\PermissionController');

    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::resource('dinas','DinasController');

    Route::post('lists/users', 'Admin\HomeController@lists')->name('admin.dashboard.lists');

    Route::resource('settings', 'SettingsController');
});

// PJLP
Route::group(['middleware' => ['role:pjlp|staff', 'auth']], function () {
    Route::post('attendances/lists', 'AttendancesController@lists')->name('attendances.lists');
    Route::get('dashboard-pjlp', 'HomeController@index')->name('dashboard');
    Route::post('attendance', 'AttendancesController@store')->name('attendance.store');
    Route::get('attendance', 'AttendancesController@index')->name('attendance.index');
    Route::resource('dinas','DinasController');
    Route::post('paid-leaves/sick', 'PaidLeavesController@sick')->name('paid-leave.sick');
    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::post('update-password', 'UserController@updatePassword')->name('update-password');
});

// Admin
Route::group(['middleware' => ['role:admin', 'auth']], function () {

});

Route::group(['middleware' => ['auth']], function () {
    Route::post('auth/sip', 'Auth\LoginController@loginFromOtherSite');
});

resources/views/layouts/module/footer.blade.php
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 3.2.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights
    reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

resources/views/layouts/module/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{{auth()->user()->hasRole('pjlp') ? route('dashboard') : route('staff.dashboard')}}" class="nav-link">Home</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="#" onclick="changePassword({{auth()->user()->id}})" class="nav-link">Password</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            @component('components.logout', [
                'class' => 'nav-link',
                'icon' => ''
            ])

            @endcomponent
            {{-- <a href="#" class="nav-link">Contact</a> --}}
        </li>
        {{-- <li class="nav-item dropdown d-sm-inline-block">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                <span class="badge badge-warning navbar-badge"  id="badge-counting-notification">15</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left">
                <span class="dropdown-item dropdown-header" id="counting-notification">15 Notifications</span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-envelope mr-2" id="notifikasi-pengajuan-cuti"></i> Pengajuan Cuti Baru
                    <span class="float-right text-muted text-sm">3 mins</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-users mr-2" id="notifikasi-perjalanan-dinas"></i> 8 friend requests
                    <span class="float-right text-muted text-sm">12 hours</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-file mr-2"></i> 3 new reports
                    <span class="float-right text-muted text-sm">2 days</span>
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
            </div>
        </li> --}}
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Navbar Search -->
        {{-- <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block">
                <form class="form-inline">
                    <div class="input-group input-group-sm">
                        <input class="form-control form-control-navbar" type="search" placeholder="Search"
                            aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search"></i>
                            </button>
                            <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li> --}}

        <!-- Messages Dropdown Menu -->
        {{-- <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-comments"></i>
                <span class="badge badge-danger navbar-badge">3</span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{{asset('v2/dist/img/user1-128x128.jpg')}}" alt="User Avatar"
                            class="img-size-50 mr-3 img-circle">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Brad Diesel
                                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">Call me whenever you can...</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{{asset('v2/dist/img/user8-128x128.jpg')}}" alt="User Avatar"
                            class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                John Pierce
                                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">I got your message bro</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <!-- Message Start -->
                    <div class="media">
                        <img src="{{asset('v2/dist/img/user3-128x128.jpg')}}" alt="User Avatar"
                            class="img-size-50 img-circle mr-3">
                        <div class="media-body">
                            <h3 class="dropdown-item-title">
                                Nora Silvester
                                <span class="float-right text-sm text-warning"><i
                                        class="fas fa-star"></i></span>
                            </h3>
                            <p class="text-sm">The subject goes here</p>
                            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
                        </div>
                    </div>
                    <!-- Message End -->
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
            </div>
        </li> --}}
        <!-- Notifications Dropdown Menu -->

        <li class="nav-item">
            <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                <i class="fas fa-expand-arrows-alt"></i>
            </a>
        </li>
        @hasrole('superadmin')
        <li class="nav-item">
            <a class="nav-link" href="{{route('settings.index')}}" >
                <i class="fas fa-cog"></i>
            </a>
        </li>
        @endhasrole
        {{-- <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                <i class="fas fa-th-large"></i>
            </a>
        </li> --}}
    </ul>
</nav>

resources/views/layouts/module/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{{asset('v2/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo"
            class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">YANIP</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{asset('v2/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2"
                    alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{auth()->user()->name}}</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search"
                    aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
           with font-awesome or any other icon font library -->
                @hasrole('staff|superadmin')
                <li class="nav-item">
                    <a href="{{route('staff.dashboard')}}" class="nav-link {{$pageTitle == 'Dashboard' ? 'active' : ''}}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard {{auth()->user()->hasRole('superadmin') ? '(Staff)' : ''}}
                        </p>
                    </a>
                </li>
                @endhasrole
                @hasrole('pjlp|superadmin')
                <li class="nav-item">
                    <a href="{{route('dashboard')}}" class="nav-link {{$pageTitle == 'Dashboard' ? 'active' : ''}}">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                @endhasrole
                @hasrole('mobile-attendance|superadmin')
                <li class="nav-item">
                    <a href="{{route('attendance.index')}}" class="nav-link {{$pageTitle == 'Absent' ? 'active' : ''}}">
                        <i class="nav-icon fas fa-camera"></i>
                        <p>
                            Presensi
                        </p>
                    </a>
                </li>
                @endhasrole

                @hasrole('staff|superadmin|admin')
                <li class="nav-item">
                    <a href="{{route('admin.attendances.index')}}" class="nav-link {{$pageTitle == 'Manajemen Absensi' ? 'active' : ''}}">
                        <i class="nav-icon fas fa-camera"></i>
                        <p>
                            Presensi {{auth()->user()->hasRole('superadmin') ? '(Staff)' : ''}}
                        </p>
                    </a>
                </li>
                @endhasrole

                @can('permission-list')
                <li class="nav-item {{$pageTitle == 'User Manajemen' || $pageTitle == 'Role Manajemen' || $pageTitle == 'Permission Manajemen' ? 'menu-open' : ''}}">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            User Manajemen
                            @can('permission-list')
                                <i class="right fas fa-angle-left"></i>
                            @endcan
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        @can('user-list')
                        <li class="nav-item">
                            <a href="{{route('users.index')}}" class="nav-link {{$pageTitle == 'User Manajemen' ? 'active' : ''}}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>User </p>
                            </a>
                        </li>
                        @endcan
                        @can('role-list')
                        <li class="nav-item">
                            <a href="{{route('roles.index')}}" class="nav-link {{$pageTitle == 'Role Manajemen' ? 'active' : ''}}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Role</p>
                            </a>
                        </li>
                        @endcan
                        @can('permission-list')
                        <li class="nav-item">
                            <a href="{{route('permissions.index')}}" class="nav-link {{$pageTitle == 'Permission Manajemen' ? 'active' : ''}}">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Permission</p>
                            </a>
                        </li>
                        @endcan
                    </ul>
                </li>
                @endcan

                @hasrole('pjlp|superadmin|admin')
                <li class="nav-item">
                    <a href="{{route('paid-leaves.index')}}" class="nav-link {{$pageTitle == 'Cuti' ? 'active' : ''}}">
                        <i class="nav-icon fas fa-user-shield"></i>
                        <p>
                            Cuti <span class="right badge badge-danger" id="notifikasi-pengajuan-cuti">{{notification(auth()->user(), 'paid-leave')}}</span>
                        </p>
                    </a>
                </li>
                @endhasrole
                @hasrole('pjlp|superadmin')
                <li class="nav-item">
                    <a href="{{route('dinas.index')}}" class="nav-link {{$pageTitle == 'dinas' ? 'active' : ''}}">
                        <i class="nav-icon fas fa-user-shield"></i>
                        <p>
                            Dinas <span class="right badge badge-danger" id="notifikasi-pengajuan-cuti">{{notification(auth()->user(), 'dinas')}}</span>
                        </p>
                    </a>
                </li>
                @endhasrole
                @hasrole('staff|superadmin')
                <li class="nav-item menu-is-opening menu-open">
                    <a href="#" class="nav-link">
                      <i class="nav-icon fas fa-tachometer-alt"></i>
                      <p>
                        Cuti
                        <i class="right fas fa-angle-left"></i>
                      </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: block;">
                      <li class="nav-item">
                        <a href="{{route('admin.paid-leaves.index')}}" class="nav-link {{$pageTitle == 'Cuti' ? 'active' : ''}}">
                          <i class="far fa-circle nav-icon"></i>
                          <p>
                            Pengajuan {{auth()->user()->hasRole('superadmin') ? '(Staff)' : ''}} <span class="right badge badge-danger" id="notifikasi-pengajuan-cuti">{{notification(auth()->user(), 'paid-leave')}}</span>
                          </p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{{route('admin.paid-leaves.users.lists')}}" class="nav-link {{$pageTitle == 'Cuti Users' ? 'active' : ''}}">
                          <i class="far fa-circle nav-icon"></i>
                          <p>Users</p>
                        </a>
                      </li>
                      <li class="nav-item">
                        <a href="{{route('admin.sick-leaves.index')}}" class="nav-link {{$pageTitle == 'Cuti Sakit' ? 'active' : ''}}">
                          <i class="far fa-circle nav-icon"></i>
                          <p>
                            Sakit {{auth()->user()->hasRole('superadmin') ? '(Staff)' : ''}} <span class="right badge badge-danger" id="notifikasi-pengajuan-cuti">{{notification(auth()->user(), 'sick')}}</span>
                          </p>
                        </a>
                      </li>
                    </ul>
                  </li>
                <li class="nav-item">
                    <a href="{{route('admin.dinas.index')}}" class="nav-link {{$pageTitle == 'dinas' ? 'active' : ''}}">
                        <i class="nav-icon fas fa-user-shield"></i>
                        <p>
                            Dinas {{auth()->user()->hasRole('superadmin') ? '(Staff)' : ''}} <span class="right badge badge-danger" id="notifikasi-pengajuan-cuti">{{notification(auth()->user(), 'dinas')}}</span>
                        </p>
                    </a>
                </li>
                @endhasrole
                <li class="nav-item">
                    @component('components.logout', [
                        'class' => 'nav-link',
                        'icon' => 'nav-icon fas fa-sign-out'
                    ])

                    @endcomponent
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>