routes/web.php
<?php

use App\Http\Controllers\SettingsController;
use App\Models\User;
use App\Scopes\YanipScope;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use App\Http\Middleware\TenantMiddleware;
use App\Http\Controllers\TenantsController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\AttendancesController;
use App\Http\Controllers\auth\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('auth/login/index');
});


Route::namespace('Auth')->name('auth.')->prefix('auth/')->group(function ()
{
    Route::name('login.')->prefix('login/')->group(function ()
    {
        Route::get('index',[LoginController::class, 'index'])->name('index');
        Route::post('process',[LoginController::class, 'store'])->name('store');
    });
    Route::name('register.')->prefix('register/')->group(function ()
    {
        Route::get('/index', [RegisterController::class, 'index'])->name('index');
        Route::get('/proccess', [RegisterController::class, 'store'])->name('store');
    });
    Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
});

/**
 * Admin Area
 */
Route::group(['middleware' => ['role:superadmin|staff|admin', 'auth']], function () {

    Route::name('admin.')->prefix('/admin')->group(function ()
    {
        // Route::get('attendances/export')
        Route::post('attendances/lists', 'Admin\AttendancesController@lists')->name('attendances.lists');
        Route::post('attendances/lists/filter', 'Admin\AttendancesController@show')->name('attendances.lists.filter');
        Route::post('paid-leaves/lists', 'Admin\PaidLeaveController@lists')->name('paid-leaves.lists');
        Route::post('dinas/lists', 'Admin\DinasController@lists')->name('dinas.lists');

        Route::get('paid-leaves/show/{cat_id}/{user_id}', 'Admin\PaidLeaveController@showByCatIDnUserID')->name('paid-leaves.showByCatIDnUserID');
        Route::get('paid-leaves/users', 'Admin\PaidLeaveController@lists_users')->name('paid-leaves.users.lists');
        Route::resource('paid-leaves', 'Admin\PaidLeaveController');
        Route::resource('sick-leaves', 'Admin\SickLeaveController');

        Route::resource('attendances', 'Admin\AttendancesController');
        Route::resource('dinas', 'Admin\DinasController');

        Route::get('/clear-cahce', function (){Artisan::call('cache:clear');});
        Route::post('update-password', 'UserController@updatePassword')->name('update-password');
    });

});

Route::group(['middleware' => ['auth']], function () {
    Route::get('dashboard', 'Admin\HomeController@index')->name('staff.dashboard');
    Route::get('dashboard/show-detail/{user_id}/{module}', 'Admin\HomeController@show')->name('show.detail.module');
    Route::post('notifications/store', 'NotificationController@store')->name('send.notification.store');
});


// Superadmin
Route::group(['middleware' => ['role:superadmin|staff', 'auth']], function () {

    Route::post('import', 'Admin\AttendancesController@import')->name('attendance.import');
    Route::get('export', 'Admin\AttendancesController@export')->name('attendance.export');

    Route::resource('users','Admin\UserController');
    Route::post('users', 'Admin\UserController@import')->name('users.import');
    Route::post('users/store', 'Admin\UserController@store')->name('users.store');
    Route::resource('roles','Admin\RoleController');
    Route::resource('permissions','Admin\PermissionController');

    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::resource('dinas','DinasController');

    Route::post('lists/users', 'Admin\HomeController@lists')->name('admin.dashboard.lists');

    Route::resource('settings', 'SettingsController');
});

// PJLP
Route::group(['middleware' => ['role:pjlp|staff', 'auth']], function () {
    Route::post('attendances/lists', 'AttendancesController@lists')->name('attendances.lists');
    Route::get('dashboard-pjlp', 'HomeController@index')->name('dashboard');
    Route::post('attendance', 'AttendancesController@store')->name('attendance.store');
    Route::get('attendance', 'AttendancesController@index')->name('attendance.index');
    Route::resource('dinas','DinasController');
    Route::post('paid-leaves/sick', 'PaidLeavesController@sick')->name('paid-leave.sick');
    Route::post('paid-leaves/print', 'PaidLeavesController@print')->name('paid-leave.print');
    Route::resource('paid-leaves','PaidLeavesController');
    Route::post('update-password', 'UserController@updatePassword')->name('update-password');
});

// Admin
Route::group(['middleware' => ['role:admin', 'auth']], function () {

});

Route::group(['middleware' => ['auth']], function () {
    Route::post('auth/sip', 'Auth\LoginController@loginFromOtherSite');
});

app/Http/Controllers/Admin/PaidLeaveController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\PaidLeave;
use App\Models\ServicesDetail;
use App\Models\User;
use App\Repository\PaidLeave\PaidLeaveRepository;
use App\Traits\PaidLeaveTrait;
use Illuminate\Http\Request;

class PaidLeaveController extends Controller
{
    use PaidLeaveTrait;
    protected $paidLeave;
    public function __construct(PaidLeaveRepository $paidLeave) {
        $this->paidLeave = $paidLeave;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::role(['pjlp'])->with('PaidLeaves')->get()->toArray();
        $users = PaidLeave::whereFlag('submit')->get();
        return view('staff.pages.paidleaves.index', [
            'users' => $users,
            'pageTitle' => 'Cuti'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $update = $request->sick_date ? $this->updateSickLeave($request) : $this->updateStatus($request);
        return array('success' => true, 'message' => $update['message']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->calculatePaidLeave(User::find($id)->role(['pjlp'])->with(['PaidLeaves' => function($query) use($id) {
            return $query->whereUserId($id)->get()->toArray();
        }])->get()->toArray());
        return $user['pjlp'];
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request)
    {
        $cat_id = array_search($request->paid_leave_name, PaidLeave::PAID_LEAVE_TYPES);
        return $this->paidLeave->FilterPaidLeaveBasedONCategoryNUserID($cat_id, (int)$request->user_id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function lists(Request $request) {
        // Page Length
        $pageNumber = ( $request->start / $request->length )+1;
        $pageLength = $request->length;
        $skip       = ($pageNumber-1) * $pageLength;

        // Page Order
        $orderColumnIndex = $request->order[0]['column'] ?? '0';
        $orderBy = $request->order[0]['dir'] ?? 'desc';


        // Search
        //  get data from Paid Leave table
        $search = $request->search;
        $month = $request->month;
        $status = $request->status;
        $query = PaidLeave::getPaidLeaveTenant($search, $month, $status);

        // $orderByName = 'name';
        // switch($orderColumnIndex){
        //     case '0':
        //         $orderByName = 'name';
        //         break;
        //     case '1':
        //         $orderByName = 'email';
        //         break;
        // }
        // $query = $query->orderBy($orderByName, $orderBy);
        $recordsFiltered = $recordsTotal = $query->count();
        $users = $query->skip($skip)->take($pageLength)->get();

        return response()->json(["draw"=> $request->draw, "recordsTotal"=> $recordsTotal, "recordsFiltered" => $recordsFiltered, 'data' => $users], 200);
    }

    function lists_users() {
        $users = $this->calculatePaidLeave(User::role(['pjlp'])->whereNotIn('id', [5, 6, 7, 8, 9])->with(['PaidLeaves' => function($query){
            return $query->whereFlag('approved')->get()->toArray();
        }])->orderBy('name')->get()->toArray());
        return view('staff.pages.paidleaves.users', [
            'pageTitle' => 'Cuti Users',
            'users' => $users
        ]);

    }

    public function showByCatIDnUserID($cat_id, $user_id) {
        $data = $this->paidLeave->FilterPaidLeaveBasedONCategoryNUserID($cat_id, $user_id);
        return $data;
    }

}

app/Http/Controllers/PaidLeavesController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Models\PaidLeave;
use Illuminate\Http\Request;
use App\Traits\PaidLeaveTrait;
use Novay\WordTemplate\WordTemplate;
use Illuminate\Support\Facades\Artisan;
use App\Repository\PaidLeave\PaidLeaveRepository;

class PaidLeavesController extends Controller
{
    use PaidLeaveTrait;

    protected $paidLeave;
    public function __construct(PaidLeaveRepository $paidLeave) {
        $this->paidLeave = $paidLeave;
    }
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $users = $this->calculatePaidLeave(User::role(['pjlp'])->with(['PaidLeaves' => function($query){
            return $query->whereFlag('approved')->get()->toArray();
        }])->get()->toArray());

        return view('admin.pages.paidleaves.index', [
            'pageTitle' => 'Cuti',
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create(Request $request)
    {
        $calculatePaidLeave = $this->calculatePaidLeave(User::role(['pjlp'])->with(['PaidLeaves' => function($query){
            return $query->whereFlag('approved')->get()->toArray();
        }])->get()->toArray());
        return array('remains' => $calculatePaidLeave[auth()->user()->name]['amount_of_leave_paid'][PaidLeave::PAID_LEAVE_TYPES[$request->paid_leave_cat_id]]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($request->leave_date == null) {
            redirect('/paid-leaves')->with(['fail' => 'gagal Mengajukan Cuti. Mohon Tanggal Diisi']);
        }
        if ($request->explaination == null) {
            redirect('/paid-leaves')->with(['fail' => 'gagal Mengajukan Cuti. Mohon Deskripsi Diisi']);
        }
        $request['list_date_paid_leave'] = explode(',', $request->leave_date);
        $request['days'] = count($request->list_date_paid_leave);
        $request['leave_date'] = date('Y-m-d');
        if ($request->sick_date) {
            $submit_sick = $this->updateSickLeave($request);
            return redirect()->back()->with(['success' => $submit_sick['message']]);
        }else{
            if ($request->days > 0) {
                $calculatePaidLeave = $this->calculatePaidLeave(User::whereId(auth()->user()->id)->with('PaidLeaves')->get()->toArray());
                if ($this->isAmountPaidLeaveLeft($calculatePaidLeave[auth()->user()->name]['amount_of_leave_paid'][PaidLeave::PAID_LEAVE_TYPES[$request->category_leave_id]], $request->days)) {
                    if($this->paidLeave->create($request->all())['success']) {
                        return redirect('/paid-leaves')->with(['success' => 'Berhasil Mengajukan Cuti']);
                    }
                }
                return redirect('/paid-leaves')->with(['fail' => 'gagal Mengajukan Cuti. Tidak ada sisa Cuti']);
            } return redirect('/paid-leaves')->with(['fail' => 'gagal Mengajukan Cuti. Jumlah Cuti  Melebihi Batas Minimum']);
        }
    }

    /**
     * Display the specified resource.
     *
     */
    public function show($id)
    {
        $data = $this->paidLeave->FilterPaidLeaveBasedONCategoryNUserID($id, auth()->user()->id);
        return $data;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(PaidLeave $paidLeave)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cutis  $cutis
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PaidLeave $paidLeave)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @return array
     */
    public function destroy($paid_leave_id)
    {
        if (PaidLeave::findOrFail($paid_leave_id)->delete()) {
            return ['success' => 'Cuti Berhasil Dibatalkan'];
        } return ['fail' => 'Cuti Gagal Dibatalkan'];
    }

    public function print(Request $request) {
        Artisan::call('cache:clear');
        return $this->getLeaveLetter($request->id);
    }

    public function sick(Request $request) {
        $update = $request->sick_date ? $this->updateSickLeave($request) : $this->updateStatus($request);
        return redirect()->back()->with(['success' => 'Berhasil Mengajukan Sakit']);
    }
}

resources/views/admin/pages/paidleaves/create.blade.php
@extends('layouts.app-lte')
@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @include('components.alert')
        <div class="row">
            <div class="col-md-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <div class="pull-right">
                                <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
                            </div>
                        </h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">

                        {!! Form::open(array('route' => 'admin.roles.store','method'=>'POST')) !!}
                        <div class="row">
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Name:</strong>
                                    {!! Form::text('name', null, array('placeholder' => 'Name','class' =>
                                    'form-control')) !!}
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Permission:</strong>
                                    <br />
                                    @foreach($permission as $value)
                                    <label>{{ Form::checkbox('permission[]', $value->id, false, array('class' =>
                                        'name')) }}
                                        {{ $value->name }}</label>
                                    <br />
                                    @endforeach
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                        {!! Form::close() !!}

                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        Footer
                    </div>
                    <!-- /.card-footer-->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
</section>
<!-- /.content -->
@endsection
@section('js-section')

@endsection

resources/views/admin/pages/paidleaves/index.blade.php
@extends('layouts.app-lte')
@section('css-section')
<link rel="stylesheet" href="{{asset('v2/dist/css/datepicker.css')}}">
<style>
    .info-box:hover {
        -webkit-box-shadow: 1px 10px 12px -10px rgba(0,0,0,0.95);
        -moz-box-shadow: 1px 10px 12px -10px rgba(0,0,0,0.95);
        box-shadow: 1px 6px 20px -15px rgba(0,0,0,0.95);
        border: 1px solid;
    }
    .info-box:active {
        -webkit-box-shadow: 1px 10px 12px -10px rgba(0,0,0,0.95);
        -moz-box-shadow: 1px 10px 12px -10px rgba(0,0,0,0.95);
        box-shadow: 1px 6px 20px -15px rgba(0,0,0,0.95);
        border: 1px solid;
    }

    .loader {
        border: 16px solid #f3f3f3; /* Light grey */
        border-top: 16px solid #3498db; /* Blue */
        border-radius: 50%;
        width: 120px;
        height: 120px;
        animation: spin 2s linear infinite;
        margin: auto;
    }

    @keyframes spin {
        0% { transform: rotate(0deg); }
        100% { transform: rotate(360deg); }
    }
</style>

@endsection
@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        @include('components.alert')
        <div id="alert-paid-leave" class="alert alert-success alert-dismissible fade show" role="alert" style="display: none;">
            <strong> Berhasil!</strong> Cuti berhasil di terima, selamat Cuti :).
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="color:white">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Ajukan Cuti</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        {!! Form::open(array('route' => 'paid-leaves.store','method'=>'POST', 'id' =>
                        'form-submit-paid-leave')) !!}
                        @php
                        $data = App\Models\PaidLeaveCat::whereNotIn('id', [2, 3, 4])->pluck('name', 'id')->toArray();
                        @endphp
                        @component('components.select.leave-paid', [
                            'id' => 'leave_paid',
                            'data' => $data
                        ])

                        @endcomponent
                        {{-- <div class="form-group">
                            <strong>Jumlah Hari:</strong>
                            {!! Form::number('days', null, array('placeholder' => 'Jumlah Hari Cuti','class' =>
                            'form-control', 'id' => 'jumlah')) !!}
                        </div> --}}
                        <div class="form-group">
                            <strong>Pilih Hari:</strong>
                            {{-- {!! Form::date('leave_date', '', ['class' => 'form-control date-paid-leave']) !!} --}}
                            <input name="leave_date" type="text" class="form-control date-paid-leave" placeholder="Pilih Tanggal">
                            <span id="remianing_paid_leave" class="text-danger" id=""></span>
                        </div>
                        <div class="form-group">
                            <strong>Alasan:</strong>
                            {!! Form::textarea('explaination', '', ['class' => 'form-control', 'rows' => 3, 'cols' =>
                            2]) !!}
                        </div>
                        <div class="form-group">

                            {!! Form::submit('Simpan', ['class' => 'btn btn-block btn-success']) !!}
                        </div>
                        {!! Form::close() !!}

                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
            <div class="col-md-8">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Sisa Cuti</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                            <button type="button" class="btn btn-tool" data-card-widget="remove" title="Remove">
                                <i class="fas fa-times"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row d-flex justify-content-center">
                            @foreach ($users as $name => $value)
                            @if ($value['id'] == auth()->user()->id)
                            @foreach ($value['amount_of_leave_paid'] as $key => $item)
                            @php $cat_id = array_search($key, App\Models\PaidLeave::PAID_LEAVE_TYPES)@endphp

                            <div class="col-lg-2 col-md-6 col-xs-12 col-sm-12" style="cursor: pointer;" onclick="detail_paid_leave({{$cat_id}})" id="box-sisa-cuti">
                                <a href="#" style="color: black;">
                                    <div class="info-box" style="text-align: center;">
                                        <div class="info-box-content">
                                            <span class="info-box-text">{{translate_in($key)}}</span>
                                            <span class="info-box-number">{{$item}}</span>
                                        </div>
                                        <!-- /.info-box-content -->
                                    </div>
                                </a>
                            </div>
                            @endforeach
                            @endif
                            @endforeach
                        </div>
                        {{-- {!! $roles->render() !!} --}}

                    </div>
                </div>
                <!-- /.card -->

                <!-- card detail -->
                <div class="card" id="detail">
                    <div class="card-header">
                        <h3 class="card-title">Detail Cuti</h3>

                    </div>
                    <div class="card-body">
                        <div class="loader" style="display: none;"></div>
                        <div class="row">
                            <div class="col-12">
                                <div class="not-avail"></div>
                                <div class="timeline">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
<!-- /.content -->
@endsection
@section('js-section')
<script src="https://js.pusher.com/8.2.0/pusher.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.3.0/js/bootstrap-datepicker.js"></script>

<script>

    $('.date-paid-leave').datepicker({
        multidate: true,
        format: 'dd-mm-yyyy',
    });

    function detail_paid_leave(params) {
        $('.loader').show();

        $('.timeline').html('');
        var url = "{{route('paid-leaves.show', ':slug')}}";
        url = url.replace(':slug', params)
        $.get(url,
            function (data, textStatus, jqXHR) {
                if (data.length == 0) {
                    $('.loader').hide();
                    $('.timeline').html('Anda Belum Mengajukan Cuti');
                }
                var html = ``;
                for (let index = 0; index < data.length; index++) {
                    const element = data[index];
                    $('.timeline').html('');
                    const flag = element.flag == 'submit' ? 'primary' : element.flag == 'approved' ? 'success' : 'danger'
                    const flag_text = element.flag == 'submit' ? 'Mengajukan' : element.flag == 'approved' ? 'Disetujui' : 'Ditolak'
                    const button_flag_cuti = `<span class="badge badge-${flag}">${flag_text}</span>`
                    const button_download_surat_cuti = element.flag == 'approved' ? `<button onclick="event.preventDefault(); document.getElementById('${element.id}').submit();" class="btn btn-primary btn-sm">Download Surat Cuti</button>` : ''
                    const button_cancel_surat_cuti = element.flag == 'submit' ? `<span onclick="cancel('${element.id}')" style="float: right; margin: 3px" class="btn btn-danger btn-sm"><i class="fas fa-times"></i> Batalkan</span>` : '';
                    // var list_date_leave = `<ul>`
                    // for (let index = 0; index < element.lists_date_paid_leave.length; index++) {
                    //     const item = element.lists_date_paid_leave[index];
                    //     list_date_leave += `<li>${item}</li>`
                    // }
                    // list_date_leave += `</ul>`
                    html += `
                            <div class="time-label">
                              <span class="bg-${flag}">${element.submit_leave_day}</span>
                            </div>

                            <div>
                              <i class="fas fa-history bg-blue"></i>
                              <div class="timeline-item">
                                ${button_cancel_surat_cuti}
                                <h3 class="timeline-header">Status : ${button_flag_cuti}</h3>
                                <div></div>
                                <div class="timeline-body">
                                  ${element.explaination}
                                  <br>Banyak Cuti: <strong>${element.days} Hari</strong>
                                  <br>Tanggal Cuti: <strong>${element.lists_date_leave}</strong>
                                </div>
                                <div class="timeline-footer">
                                  ${button_download_surat_cuti}
                                    <form id="${element.id}" method="post" action="{{route('paid-leave.print')}}" style="display:none;">
                                        @csrf
                                        <input text="hidden" name="id" value="${element.id}"/>
                                    </form>
                                </div>
                              </div>
                            </div>`;
                    $('.loader').hide();

                    $('.timeline').html(html);
                }
            },
            "JSON"
        );
    }

    $('#leave_paid').on('change', function() {
        $("#form-submit-paid-leave input").prop("disabled", false);
        $.get("{{route('paid-leaves.create')}}", {'paid_leave_cat_id':this.value},
            function (data, textStatus, jqXHR) {
                if (data.remains == 0) {
                    alert('Cuti Sudah Habis')
                    $("#form-submit-paid-leave input").prop("disabled", true);
                }
                $("#remianing_paid_leave").html(`Sisa Cuti: ${data.remains}`);
                $('input[name=days]').attr('max', data.remains)
            },
            "JSON"
        );
    });

    Pusher.logToConsole = true;

    var pusher = new Pusher('d298640228c2f3ac76ff', {
    cluster: 'ap1'
    });

    var channel = pusher.subscribe('my-channel');
    channel.bind('my-event', function(data) {
        console.log(data);
        // $('#alert-paid-leave').show('slow');
    });

    function cancel(paid_leave_id) {
        var url = "{{route('paid-leaves.destroy', ':id')}}"
        url = url.replace(':id', paid_leave_id)
        $.ajax({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            type: "POST",
            data: {'_method': 'delete'},
            url: url,
            dataType: "json",
            success: function (response) {
                if (response.success) {
                    alert(response.success)
                    location.reload();
                }
            }
        });
    }


</script>

@endsection

resources/views/admin/pages/paidleaves/show.blade.php
@extends('layouts.app-lte')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2> Show Role</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('roles.index') }}"> Back</a>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Name:</strong>
            {{-- {{ $role->name }} --}}
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Permissions:</strong>
            @if(!empty($rolePermissions))
                @foreach($rolePermissions as $v)
                    <label class="label label-success">{{ $v->name }},</label>
                @endforeach
            @endif
        </div>
    </div>
</div>
@endsection